// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF3dnNkr_JUFuRjCm-8bygX2Su2curNeA',
    appId: '1:631556728870:web:15e598fec71b7670869ee7',
    messagingSenderId: '631556728870',
    projectId: 'foodie-43fab',
    authDomain: 'foodie-43fab.firebaseapp.com',
    storageBucket: 'foodie-43fab.appspot.com',
    measurementId: 'G-E25LVLK3WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASF0wvjN-TrHPyiGENxBurSuodnm5Whcw',
    appId: '1:631556728870:android:e95f60931c7dc5e7869ee7',
    messagingSenderId: '631556728870',
    projectId: 'foodie-43fab',
    storageBucket: 'foodie-43fab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfPPpkgCFp1BWPM8Uu81L3l-EPZ5qTqdo',
    appId: '1:631556728870:ios:7142c46fa015af78869ee7',
    messagingSenderId: '631556728870',
    projectId: 'foodie-43fab',
    storageBucket: 'foodie-43fab.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfPPpkgCFp1BWPM8Uu81L3l-EPZ5qTqdo',
    appId: '1:631556728870:ios:7142c46fa015af78869ee7',
    messagingSenderId: '631556728870',
    projectId: 'foodie-43fab',
    storageBucket: 'foodie-43fab.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF3dnNkr_JUFuRjCm-8bygX2Su2curNeA',
    appId: '1:631556728870:web:880170792395fe5b869ee7',
    messagingSenderId: '631556728870',
    projectId: 'foodie-43fab',
    authDomain: 'foodie-43fab.firebaseapp.com',
    storageBucket: 'foodie-43fab.appspot.com',
    measurementId: 'G-Y4FPHSMGP9',
  );
}
